server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecart
    username: root
    password: root
  jpa:
    database: MYSQL
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect